import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

import "../globals.css";
import AdminSidebar from "@/components/admin-sidebar";
import ToastProvider from "@/providers/toast-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className="md:flex md:flex-row ">
          <ToastProvider />
          <AdminSidebar />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
